### ISSUE TITLE
Adding labels when creating PRs

### ISSUE THREAD

**Issue by ntravis** [pyupio/pyup#110]
Hi,

We've had a feature request from one of our devs regarding PRs generated by pyup. Several of our teams are using Waffle.io for tracking PRs and Issues and would like to be able define a repo-specific label to be applied to all PRs generated by pyup for that repo. I think the workflow would look like this:

- Add repo in pyup
- On the repo specific screen, an optional (unused if empty) label field would be available
- If updated with a value, any existing PRs generated by pyup would have that label edited on to the PRs and new PRs would be generated with the label value

I believe that pygithub has support for all of this already from a quick perusal. I've sent this to our dev to confirm that would be his expected workflow. Does this sound in-spec for pyup?

Caveat: this would ideally be open to accounts with org perms, rather than only limited to the original creation account.

**Comment by jayfk** [comment]
I really like that feature!

The groundwork is in 29c2d29a4d53a5364d802a1b054998e91581cff1. It's live already, see https://github.com/friendly-test-bot/pyup-label-integration-test-A4e9/pull/2 for an example.

Caveat: 
* The UI on https://pyup.io isn't updated just yet. 
* It won't work for users with `public_repo` scope.

If one of your devs wants to use it right now, use the `.pyup.yml` [config file]( https://pyup.io/docs/configuration/). Here is an [example](https://github.com/friendly-test-bot/pyup-label-integration-test-A4e9/blob/master/.pyup.yml).

I can't give you an ETA on when this will be available on the https://pyup.io UI. Working with the GitHub API permission system is a major pain point right now, I probably have to rewrite a lot of functionality to support like you suggested.

Would it be okay to work around that for the time being with the config file?

**Comment by ntravis** [comment]
The .pyup.yml is a fine solution for us as we engage with several other vendors that way and prevents the end dev having to go to our password manager and getting the original account out, etc. Thanks @jayfk. If you want to save the UI/org user stuff for another day as a future enhancement, I think we can call this closed with the yml solution.

**Comment by jayfk** [comment]
Great, thanks @ntravis.
