### ISSUE TITLE
Can't add repos via pyup website

### ISSUE THREAD

**Issue by LegoStormtroopr** [pyupio/pyup#134]
When I go to `https://pyup.io/account/repos/add/` and click "Add" next to any repo nothing happens.

Opening the inspector shows this error:

![image](https://cloud.githubusercontent.com/assets/2173174/19784699/73dd3f6c-9ce2-11e6-89ed-2e413c353c91.png)

Tested on Chrome & Firefox on Windows 10.

**Comment by jayfk** [comment]
Thanks for reporting. I am able to reproduce the bug on your account.

I'll let you know once I know more.

**Comment by LegoStormtroopr** [comment]
Cheers :)

**Comment by jayfk** [comment]
This should work now.

**Comment by LegoStormtroopr** [comment]
Yup! Works a charm, thanks!
