### ISSUE TITLE
Support Environment Markers

### ISSUE THREAD

**Issue by jayfk** [pyupio/pyup#154]
Environment markers are currently not supported:

> I use Environment Markers (PEP 496) in my requirements.txt. But it seems pyup-bot doesn't know what it is and deletes them, for example in this PR: https://github.com/bayandin/devtools-proxy/pull/16/files. Hope it will be possible to keep the environment markets in requirements.txt.

**Comment by jayfk** [comment]
cc @bayandin

**Comment by jayfk** [comment]
Fixed in https://github.com/pyupio/pyup/commit/c38653d9d42b2677fc083abe2b82c82fa204fc6a.

See commit: https://github.com/jayfk/devtools-proxy/pull/1/commits/3c691c7a14cca9fa42fcc9f2df4bdf822d4c01fa

**Comment by bayandin** [comment]
@jayfk wow! That's amazing, thanks!
