### ISSUE TITLE
package update not being noticed

### ISSUE THREAD

**Issue by samuelcolvin** [pyupio/pyup#172]
I updated [python-pdf](https://pypi.python.org/pypi/python-pdf) three days ago (16th) however no pull request has been created for the change and nothing shows in the pyup interface.

The update was from [v0.23](https://pypi.python.org/pypi/python-pdf/0.23) to v0.3.

Unfortunately the repo using python-pdf is private so I can't provide a link to the lack of PR.

Possibly related: the badge from [shields.io](http://shields.io) hasn't updated either. I guess it's remotely possibly you use the same mechanism of prompting updates and pypi had a problem where the prompt wasn't fired for this package?

**Comment by jayfk** [comment]
That's a versioning problem, `<major>.<minor>.<patch>`.

The bot compares the third minor release `0.3` with the twentythird minor release `0.23` to see if an update is available:

The code basically looks like this:
```
>>> from pkg_resources import parse_version
>>> parse_version("0.3") > parse_version("0.23")
False
```

The correct versioning would be to use the second minor, third patch release `0.2.3` for `python-pdf`:

```
>>> parse_version("0.3") > parse_version("0.2.3")
True
```

I'm afraid there's nothing I can do about this.

**Comment by jayfk** [comment]
To make this more clear, let's take a look at Django as an example.

The Django LTS release is currently at `1.8.17`, if they were using the same versioning scheme, `1.8.3` would be newer than this. Or, if we compare the latest `1.10.3` to `1.3`, then `1.3` would win.

**Comment by samuelcolvin** [comment]
I completely missed that, caused by my ignorance 2 years ago when I first built the package. My mistake.
