### ISSUE TITLE
Pyup Website Bug

### ISSUE THREAD

**Issue by ntravis** [pyupio/pyup#173]
When accessing pyup from a non-logged in browser, you end up on a page without any "bail out" behavior, e.g. no links to homepage or the account login. My particular URL structure was of this type:
    `https://pyup.io/repos/github/org/repo/commits/commit/`

Out of the two available options already on page, the large logo is a good candidate or the small pyup in the bottom left

    <div class="padding-top-40">
        <img src="https://pyup.io/static/images/logo.png" class="img img-responsive"/>
    </div>
    ...
    <div class="col-md-6">
        pyup
    </div>

**Comment by jayfk** [comment]
fixed! thanks, @ntravis 🎄
