### ISSUE TITLE
Update requirements with the correct sep. character

### ISSUE THREAD

**Issue by jayfk** [pyupio/pyup#183]
> One thing that gets me though is that your generated files just have a space before the comment in the requirements file, where as mine have tabs, leading to diffs similar to this

> -Jinja2==2.9.4 # via flask
+jinja2==2.9.4             # via flask

cc @jimjkelly

**Comment by jimjkelly** [comment]
Just noting in case you forget or someone else comes across this, the formatting in question was lost.  It looks similar to:

```bash
-Jinja2==2.9.4         # via flask
+jinja2==2.9.4 # via flask
```
