### ISSUE TITLE
openpyxl releases doesn't match pypi

### ISSUE THREAD

**Issue by samuelcolvin** [pyupio/pyup#198]
With github integration, we're getting constant pull requests "Update openpyxl to 2.4.3".

That version doesn't exist on pypi. We've tried closing the PR and deleting the branch and another PR is always created.

![image](https://cloud.githubusercontent.com/assets/4039449/22595579/f5f4edee-ea1f-11e6-8435-3b52989db52a.png)

https://pyup.io/changelogs/openpyxl/ doesn't match https://pypi.python.org/pypi/openpyxl/json at all. Lots of version (2.5, 3.2, 3.3) don't exist on pypi.

**Comment by jayfk** [comment]
Could you try adding a filter to the line that disables the `2.4.3` release completely? I'm going to disable the `2.4.3` release on the server in a second, just to be sure.

```
openpyxl==2.4.2 # pyup: !=2.4.3
```

The bot takes PyPi as its source of truth and in fact PyPi reports `2.4.3` to be the latest release.

```
import requests

r = requests.get('https://pypi.python.org/pypi/openpyxl/json')
r.json()['info']['version']

>>> '2.4.3'
```

although the release has no install candidate

```
r.json()['releases']['2.4.3']

>>> []
```

It could be that the release was somehow pulled from PyPi.

Regarding the changelogs: That seems to be a bug in the changelog parser, I've opened a new issue at https://github.com/pyupio/changelogs/issues/4 to investigate.

**Comment by jayfk** [comment]
Pulled `2.4.3` from pyup.io. It should now be safe to remove all open PRs.

**Comment by samuelcolvin** [comment]
Thanks for looking into this.

Perhaps pyup could check a release is available before suggesting the upgrade? (This problem is rare and not very serious so if that's difficult I quite understand if it can't).

**Comment by jayfk** [comment]
That'd probably be the best thing to do, indeed.
