### ISSUE TITLE
add gitlab integration

### ISSUE THREAD

**Issue by managai** [pyupio/pyup#200]
I'm interested to adopt pyup for my gitlab hosted projects.
Future plans include support to different git hosting providers?

I'm not sure I'm able to engage this task, but where I can find some info on how to start?
I would need only to properly create a pyup/providers/gitlab.py  file?

**Comment by TeNNoX** [comment]
This will probably be useful (as equivalent for the python-github wrapper):
https://github.com/gpocentek/python-gitlab

**Comment by jayfk** [comment]
> Future plans include support to different git hosting providers?

Yes! But probably not very soon. There are still too few users on gitlab for this to make sense from a business point of view.

> I'm not sure I'm able to engage this task, but where I can find some info on how to start?
> I would need only to properly create a pyup/providers/gitlab.py file?

Exactly. The only thing besides that is to tell the bot to use the gitlab provider, see https://github.com/pyupio/pyup/blob/master/pyup/bot.py#L15.

This won't be an easy task, though. Every API comes with its own set of quirks you have to deal with.

**Comment by jayfk** [comment]
Closing this as an duplicate of #55.
