### ISSUE TITLE
500 error at https://pyup.io/account/repos/fetch-repos/

### ISSUE THREAD

**Issue by samuelcolvin** [pyupio/pyup#204]
Trying to sync my repos I'm getting an alert: "An unknown error occurred. Please contact support at support@pyup.io."

Looking in the console, I'm getting a 500 response from `https://pyup.io/account/repos/fetch-repos/` sure enough if I go to that url I get 500 too. 

I got this the other day, I think it was intermittent then but seems to be constant now.

**Comment by samuelcolvin** [comment]
I'm trying to re-add a repo https://github.com/aio-libs/aiohttp-devtools which was transferred from myself to that organisation, perhaps this is the cause of the error?

**Comment by jayfk** [comment]
I've just updated the entry manually, you should be good to go!

> I'm trying to re-add a repo https://github.com/aio-libs/aiohttp-devtools which was transferred from myself to that organisation, perhaps this is the cause of the error?

Exactly this. Have you transferred the repo, or was there a step in between? This would help me a lot to debug this.

**Comment by samuelcolvin** [comment]
Thanks for updating. I just did standard github: settings > transfer ownership. I transferred it about a week ago.

**Comment by samuelcolvin** [comment]
I'm getting this again

> An error has occurred on this page. We are probably already working on the problem, so please try again later.

Trying to add https://github.com/tutorcruncher/morpheus I don't think there's anything funny about this, just a vanilla open source repo.

Response headers includes `X-Sentry-ID: 1ecd58ead9e1416d99bde71a814ef852`.

**Comment by samuelcolvin** [comment]
Although I guess the fetch doesn't know which repo I'm trying to add, could well be another repo which is odd in some way and causing the problem.

**Comment by jayfk** [comment]
Yeah, just saw that flying by via Sentry. Fixed it manually, should be working again!

Looks like the sync function isn't as robust as I initially thought (although this was the first bug related to this in weeks). Have you done anything special to `samuelcolvin/Bokeh.jl`? It looks like the repo changed the internal GitHub ID, causing an IntegrityError.

**Comment by samuelcolvin** [comment]
yes, it got moved to me https://github.com/samuelcolvin/Bokeh.jl/issues/38

**Comment by samuelcolvin** [comment]
thanks for manually updating it.

**Comment by jayfk** [comment]
Ah I see. That makes sense.
