### ISSUE TITLE
HTTP 500 on the mozilla/treeherder repository requirements page

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#206]
After signing up and adding a repo, I used the "Requirements" button, which takes me to:
https://pyup.io/account/repos/github/mozilla/treeherder/

However that page HTTP 500s.

**Comment by jayfk** [comment]
Thanks for letting me know. I've got some errors on Sentry related to this issue. Somehow the requirements parser is failing to parse the hashes correctly. 

Expect this to be fixed tomorrow.

**Comment by jayfk** [comment]
Fixed!

I've also removed the repo so you can add your filters. Once you are ready, close the Initial PR, delete the branch and add the repo again.

You might also want to add a `.pyup.yml` and set a `pr_prefix` with the bug id that's used on treeherder for dependency updates. That's something I've worked on with one of the mozillians a couple of weeks ago, but I can't remember the repo name :/.

**Comment by edmorley** [comment]
Many thanks!
