### ISSUE TITLE
Document how to recreate the initial PR, without it turning into separate PRs

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#208]
After adding a repo, the initial PR was opened updating 48 packages. Unfortunately some of those packages shouldn't be updated, so will need filtering (I would have done that first, but for #207).

In the initial PR description it says:
> This is my first visit to this fine repo so I have bundled all updates in a single pull request to make things easier for you to merge.
> Close this pull request and delete the branch if you want me to start with single pull requests right away

So if I just deleted the branch, I'd end up with 40+ PRs being opened, which is pretty spammy.

Instead, I'd just like the initial PR to be updated to take into account the filters, but it's not clear how to achieve that. (Perhaps by deleting the repo from my pyup account page and re-adding?)

**Comment by jayfk** [comment]
> Perhaps by deleting the repo from my pyup account page and re-adding?

Exactly.  Since the page is currently 500ing, this will probably have to wait a bit ;).

Have you seen the prompt that opens up when adding a repo? This would probably be a good place to add a warning, what do you think?

**Comment by edmorley** [comment]
> Have you seen the prompt that opens up when adding a repo? This would probably be a good place to add a warning, what do you think?

Yeah that sounds like a good place :-)

**Comment by fmigneault** [comment]
In my case, the initial PR wasn't really verbose about anything. 
I got quite a big spam of PRs not long after. Wasted a lot of time removing all that.

https://github.com/Ouranosinc/Magpie/issues/268#issue-597697836
