### ISSUE TITLE
Spelling error in "Initial Update" message

### ISSUE THREAD

**Issue by alexwlchan** [pyupio/pyup#210]
Just saw this in an [Initial Update message](https://github.com/HypothesisWorks/hypothesis-python/issues/496) from @pyup-bot:

> Once you have closed this issue, I'll create seperate pull requests for every update as soon as I find one.

It should be spelt “separate”, not “seperate”. I’d raise a PR for it, but I can’t actually find where this string comes from in the code.

**Comment by jayfk** [comment]
Thanks!

> I’d raise a PR for it, but I can’t actually find where this string comes from in the code.

The bot running on pyup.io is using a modified Pull Request template. I've updated it.
