### ISSUE TITLE
Requirements checker tool 6000 character limit too short

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#212]
I was hoping to use https://pyup.io/tools/requirements-checker/ to preview the changes that would be made to a requirements file that is currently ignored (using `# pyup: ignore file`), so I could check my filter lines (eg `# pyup: <4`) were correct before unleashing the PRs.

However after pasting in this requirements file (with the `ignore` line omitted):
https://github.com/mozilla/treeherder/blob/ab82e6152635b8150f4a612bdba5be96131406c0/requirements/common.txt

...I get:
"Ensure this value has at most 6000 characters (it has 6111)."

I had to manually remove a couple of comment lines to get it under the limit.

With pip hashes, requirements files can now be reasonably large, so the limit is probably a bit low.

**Comment by jayfk** [comment]
Agreed. The online tool should be updated anyway, I'm not quite sure if it currently supports hashes.

You are a bug monster, @edmorley. If I ever run a beta again, I'll have to invite you :)!

**Comment by edmorley** [comment]
At some of the offices we have a posted based on https://pbs.twimg.com/media/Bl76SAwCIAA7jqX.jpg - which I try to follow :-) (Totally understand we're using pyup for free, so no expectations, but thought might as well file things I see in case it helps with paying customers too.)

**Comment by jayfk** [comment]
Upped the limit to 12k!

**Comment by edmorley** [comment]
Many thanks :-)
