### ISSUE TITLE
Link to PyPI and package repo from overview page

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#214]
One feature I miss from requires.io is the ability to jump straight to PyPI and/or the package repo from eg https://pyup.io/account/repos/github/mozilla/treeherder/

Currently if the changelog is missing, I have to Google "pypi {package name}" to get the PyPI page.

**Comment by jayfk** [comment]
This should be good now.

**Comment by edmorley** [comment]
Hi :-) I can't seem to find links to PyPI on this page?
https://pyup.io/account/repos/github/mozilla/treeherder/
