### ISSUE TITLE
Package in requirements file not detected by pyup

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#215]
Our requirements file contains the line ([link](https://github.com/mozilla/treeherder/blob/589817d6b09545f8bbfab922a7153087e0612463/requirements/common.txt#L149)):
`taskcluster==0.3.4 --hash sha256:d4fe5e2a44fe27e195b92830ece0a6eb9eb7ad9dc556a0cb16f6f2a6429f1b65`

However the pyup overview (https://pyup.io/account/repos/github/mozilla/treeherder/) does not list that package, and the bot hasn't opened a PR to update to the newer 1.2.0 release.

The package can be found here:
https://pypi.python.org/pypi/taskcluster
https://github.com/taskcluster/taskcluster-client.py

**Comment by jayfk** [comment]
I can confirm this. A quick test showed that it works without the hash being set.

**Comment by jayfk** [comment]
regex ¯\\__(ツ)_/¯

**Comment by edmorley** [comment]
Ah I see the hash was missing the equals sign. 

Pip seems to use optparse to parse the options tacked on the end of a requirements line:
https://github.com/pypa/pip/blob/548a9136525815dff41acd845c558a0b36eb1c5f/pip/req/req_file.py#L126-L130

...and that presumably supports either form.

The joys of parsing!

**Comment by edmorley** [comment]
Many thanks for fixing :-)
