### ISSUE TITLE
ldap3 changelog one version

### ISSUE THREAD

**Issue by brianmay** [pyupio/pyup#219]
Looking at https://pyup.io/changelogs/ldap3/ there is only one version - 2.2.2 (I assume this will eventually show 2.2.3), and all changelog entries appear under this version.

**Comment by jayfk** [comment]
Yep, ldap3 is a special friend...

Probably need to write a special parser for this one. I'm closing this issue here since it's related to the changelog parsing service: https://github.com/pyupio/changelogs/issues/57

Thanks for letting me know!
