### ISSUE TITLE
Error if requirement file path contains special characters

### ISSUE THREAD

**Issue by achaussier** [pyupio/pyup#221]
Hello,

Thanks for this very useful service.

I've add the service to one of my repositories (a cookiecutter template) and I had problem with a requirement file path like:
```yaml
requirements:
  - 'requirements.txt'
  - 'ansible-role-{{ cookiecutter.role_name }}'
```

Problems occurs with CLI or webui.

I've update config file to:
```yaml
requirements:
  - 'requirements.txt'
  - 'ansible-role-%7B%7B%20cookiecutter.ansible_role_name%20%7D%7D/requirements.txt'
```
It fixes the problem for CLI but not for the webui.

**Comment by jayfk** [comment]
Thanks for reporting!

Probably just a small bugfix on the internal "requirements resolver". I'll check this out tomorrow.

**Comment by jayfk** [comment]
This should be working now.

It looks like the bot failed during the update and left an empty branch behind. You probably want to delete the `pyup-update-pytest-3.0.7-to-3.1.0` branch here: https://github.com/infOpen/cookiecutter-ansible-role/branches

**Comment by achaussier** [comment]
Thanks, I'll do it now
