### ISSUE TITLE
Duplicate commit/changelogs/... with same requirement in different files

### ISSUE THREAD

**Issue by The-Compiler** [pyupio/pyup#223]
With e.g. https://github.com/qutebrowser/qutebrowser/pull/2715 the bot updated `chardet` in multiple files.

However, it did three "Update chardet from 3.0.3 to 3.0.4" commits (one per file), chardet is included three times in the table in the PR, and its changelog is shown three times.

It'd be nice if those were bundled correctly.

**Comment by jayfk** [comment]
> It'd be nice if those were bundled correctly.

Fixed! 👍
