### ISSUE TITLE
pyup creating many branches without new commits

### ISSUE THREAD

**Issue by g-k** [pyupio/pyup#224]
With security updates configured pyup is making a lot of branches without any commits here: https://github.com/mozilla-services/antenna/branches/all

Is there a way to configure pyup to not make the branches or to clean them up?
Is it safe to delete those branches or is it using the existing branch names?

**Comment by jayfk** [comment]
This looks like a bug. I'll try to reproduce this tomorrow and get back to you.

It should be safe to delete them though.

**Comment by jayfk** [comment]
Fixed in https://github.com/pyupio/pyup/commit/bb6f3b6deca828312a8625123476ab7cabd22a0c. Thanks for reporting!

**Comment by g-k** [comment]
Great! Thanks Jay!
