### ISSUE TITLE
option to not require repo write permission

### ISSUE THREAD

**Issue by g-k** [pyupio/pyup#226]
Is there a way to not require write permission (for the bot not safety cli)?

If not and assuming this is possible with the github API, I'd request the feature to send PRs from a fork to its upstream.

If I have a sensitive repo I don't want the pyup bot to have write access to I would:

1. create a github account for the bot
2. fork my repo to the bot's account
3. have the bot send PRs upstream to me

The bot working from its github account would just need read permission on my upstream and write permission to its fork.

This is an obvious abuse vector, so it might require some opt in from the upstream.

edit: the bot would need to sync its default branch with the upstream first

**Comment by jayfk** [comment]
I can fully understand that and I'd love to ship a feature that makes something like this possible.

> If not and assuming this is possible with the github API, I'd request the feature to send PRs from a fork to its upstream.

I looked into this during the beta, it's certainly possible. But, and I don't know exactly what it was, it was completely unusable from the user's and the services' point of view. As far as I remember this also generated a lot of noise via email.

I'll dig deeper into this one. 

In the meantime, you best bet is to run the bot on from the command line.

**Comment by g-k** [comment]
> In the meantime, your best bet is to run the bot on from the command line.

👍  I passed this option along.

> I looked into this during the beta, it's certainly possible. But, and I don't know exactly what it was, it was completely unusable from the user's and the services' point of view. As far as I remember this also generated a lot of noise via email.

Yeah, I'm sure that most people prefer the simplicity and quietness of the one repo option. Would you be open to a PR to implement this in the bot? I might have some time to work on this in a few weeks.

**Comment by g-k** [comment]
We've enabled github's branch protection as a workaround.
