### ISSUE TITLE
pyup bot chokes on requirements files (but not the pyup.io service)

### ISSUE THREAD

**Issue by mozbhearsum** [pyupio/pyup#227]
I've been attempting to run the pyup bot myself, because I have a repo that I'm not comfortable giving the pyup.io service write access to. I was surprised to find that instead of creating an initial PR, it created an Issue (eg: https://github.com/testbhearsum/balrog2/issues/33) claiming everything was up to date already.

If I use the service, I get a PR like https://github.com/testbhearsum/balrog/pull/3 instead.

I did some digging and it appears that the multi-line format of my requirements files is causing some issues. After https://github.com/pyupio/pyup/blob/ad58c9bd3706065e21513b9bc41222b1488c6246/pyup/requirements.py#L188 is run, "parseable_line" ends up being something like:
"asynctest==0.10.0 asynctest==0.10.0" -- which clearly is not correct.

I'm pretty sure my requirements files are OK, as pip parses them fine.

**Comment by jayfk** [comment]
Could you try installing the bot from git master? It could be that the bot is choking on the hashes.

**Comment by mozbhearsum** [comment]
Same thing with ad58c9bd3706065e21513b9bc41222b1488c6246, unfortunately.

**Comment by jayfk** [comment]
All right, that's odd. I'll try to reproduce this tomorrow, it's getting late here ;).

Could you give me the command you were trying to run?

**Comment by mozbhearsum** [comment]
No worries. I was running:
`pyup --repo=testbhearsum/balrog2 --user-token XXXXXXXX --initial`

**Comment by g-k** [comment]
Might be able to swap in the requirements file parser from pip: https://github.com/pypa/pip/blob/master/pip/req/req_file.py#L54

**Comment by jayfk** [comment]
Okay, I'm able to reproduce this locally. I don't know exactly what it is, but it will likely go away once I'm able to swap out the internal parsing library. Hopefully by the end of the week.

@g-k quoting Donald Stufft here:

> There is no supported pip API besides the CLI, it can change at any time even in micro versions. That being said, just because it can doesn't mean it will and we generally try not to break things that people are relying on unless it would be annoying to maintain compatibility. That being said, it's unsupported so if you're using it, you use it at your own risk.

**Comment by mozbhearsum** [comment]
Awesome, thanks for the quick response! I'm happy to help verify any potential fix.

**Comment by jayfk** [comment]
Fixed it in https://github.com/pyupio/pyup/commit/bd2de95fc32d0f8018bb78bdd2db2aebb96cdce7

Processing the file will take some time because `hashin` will download and hash every package that needs an update locally. 

Well, I guess the repo is named *balrog* for a reason.

**Comment by jayfk** [comment]
And available as `0.7.0` on PyPi: https://pypi.org/project/pyupio/
