### ISSUE TITLE
Getting hashes from warehouse?

### ISSUE THREAD

**Issue by jayfk** [pyupio/pyup#239]
The bot currently uses [hashin](https://github.com/peterbe/hashin) to download and calculate dependency hashes locally.

Would it make sense to use the hashes that are available from warehouse (example on https://pypi.org/pypi/requests/2.18.1/json)?

This would make the bot on requirement files with hashes a lot faster.

I know that hashed requirement files are widely used at mozilla. I'd be very interested to hear your thoughts on this @dhunt, @jezdez, @mozbhearsum, @g-k, @edmorley.

**Comment by edmorley** [comment]
I've just checked that the hashes are the same as those output by  `pip hash` (they're both SHA256 and the contents being hashed is that of the whole download, not some subset inside).

Given that, I'd say it's worth using the API. After all, for people using hashes in their requirements files, their CI run will make it obvious if that hash deviates from the actual downloaded file - and this way, someone would have to tamper with both the PyPI API response, and the actual file served.

**Comment by jayfk** [comment]
This is working fine 👍
