### ISSUE TITLE
skipping email notifications ?

### ISSUE THREAD

**Issue by asmodehn** [pyupio/pyup#242]
Any option for this in the configuration `.pyup.yml` ?

I couldn't find anything in the doc... and getting a pull request is enough of a notification personally.

**Comment by jayfk** [comment]
Email notifications are coming from GitHub. In order to disable them you need to *unwatch* the repo the bot is sending pull requests to.

**Comment by asmodehn** [comment]
Ah I see... but I still want to watch it and get notified of pull requests,
just not from pyup bot. Is there any way ?

**Comment by rafaelpivato** [comment]
That would be nice. I don't know how to ignore pull-requests but GitHub has some docs about that: https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#filtering-email-notifications

I imagine you should be able to get details for some emails you received and try filtering them.
