### ISSUE TITLE
Packages reported as non compatible with Python3

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [pyupio/pyup#243]
Hello,

I just subscribed to your very cool platform. Thanks for the works, this rocks !

I just noticed a few minor errors with packages reported as non compatible with python 3. By the way, they can be perfectly installed and used with Python 3.4/3.5/3.6

### untangle==1.1.1

![image](https://user-images.githubusercontent.com/10923599/29495812-00bfee34-85c7-11e7-93be-ca5ac2003d34.png)
![image](https://user-images.githubusercontent.com/10923599/29495820-3b0af070-85c7-11e7-949b-9d67c4e2f5b4.png)

Extract from [setup.py on github.com](https://github.com/stchris/untangle/blob/master/setup.py):
```python
setup(
    name='untangle',
    classifiers=(
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        "Programming Language :: Python :: 3.3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
    ),
)
```

### twython==3.5.0

![image](https://user-images.githubusercontent.com/10923599/29495853-cb9c809a-85c7-11e7-9901-1f572543e878.png)
![image](https://user-images.githubusercontent.com/10923599/29495851-bd8f8de4-85c7-11e7-92e3-9bfada3fce1f.png)

Extract from [setup.py on github.com](https://github.com/ryanmcgrath/twython/blob/master/setup.py):
```python
setup(
    name='twython',
    classifiers=[
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ]
)
```

**Comment by luzfcb** [comment]
@DEKHTIARJonathan Likely problem with pypi API or how the package was published in pypi

see: https://pypi.python.org/pypi/untangle/json

```
"classifiers": [],
```

**Comment by DEKHTIARJonathan** [comment]
Humm ... It feels like I should create the issue on the repositories of these packages right ?

**Comment by jayfk** [comment]
@luzfcb beat me to it. Both classifiers are outdated on PyPi

**Comment by jayfk** [comment]
> Humm ... It feels like I should create the issue on the repositories of these packages right ?

Exactly. Once they are updated, the package will show up as Python 3 compatible (+ some time for caching).

**Comment by DEKHTIARJonathan** [comment]
Alright ! Thanks for your time guys ;)
