### ISSUE TITLE
Error - Unknown Error

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [pyupio/pyup#244]
Hello there,

I'm not sure it is the right place to ask any question. I hope it is...

I have a problem with this repository: <https://pyup.io/account/repos/github/DEKHTIARJonathan/keras-datasets/>

![image](https://user-images.githubusercontent.com/10923599/29556131-29e6571c-8725-11e7-85d5-a5fb05d1761e.png)

I have a massive **Error - Unknown error** and no idea what could have cause this ... I have tried to change a few things but nothing seems to have an effect ...

Thanks for the help buddies !

Best Regards,

Jonathan

**Comment by jayfk** [comment]
It looks like the bot crashes when parsing your config file (This needs to be valid YAML). Remove the trailing `:` at https://github.com/DEKHTIARJonathan/keras-datasets/blob/master/.pyup.yml#L37-L40

Also, using `assignees` and `label_prs` won't work with public repo permissions: https://github.com/DEKHTIARJonathan/keras-datasets/blob/master/.pyup.yml#L42-L52

**Comment by DEKHTIARJonathan** [comment]
Damned ... how did I not see this ?
Thanks a lot. Problem solved

**Comment by jayfk** [comment]
Reopening this. The bot shouldn't crash with an invalid config file :)

**Comment by DEKHTIARJonathan** [comment]
@jayfk i think I may have some clue for you.

It seems that despite your correction were 100% accurate, I actually tried to **validate** my config file with a YAML Linter and it was perfectly fine.

I have retried and it is absolutely fine by any magic...

Old file: <https://github.com/DEKHTIARJonathan/keras-datasets/blob/8d9d6e3a6a464e279670733acf35156e1deba5ce/.pyup.yml>

Yaml Linter: <http://www.yamllint.com/>
![image](https://user-images.githubusercontent.com/10923599/29557249-bc6db33e-8728-11e7-9099-9d905c747d52.png)

So I am not surprised your bot didn't identified my config file as an incorrect one ...

**Comment by jayfk** [comment]
Ah, that's probably because the requirement file is an empty dict instead of a string. Thanks!

**Comment by DEKHTIARJonathan** [comment]
No problem.

**Comment by jayfk** [comment]
Thanks @DEKHTIARJonathan. I'm closing this issue and add it to https://github.com/pyupio/pyup/issues/244
