### ISSUE TITLE
Add documentation about the workflow

### ISSUE THREAD

**Issue by htgoebel** [pyupio/pyup#245]
I just closed a pull-request created by pyup-bot (pyinstaller/pyinstaller#2779) without merging and deleted the branch. Just a few seconds later pyup-bot created a new pull-request with the same update (pyinstaller/pyinstaller#2781) – which is curious.

I searched for documentation about to handle such a case and did not find one. I also did not find documentation about the workflow. Please add such documentation to https://pyup.io/docs/ Thanks.

Proposed content
- The initial update and how to handle it (e.g. what happens if you do not accept it)
- Accepting a pull-request (e.g. does pyup-bot dletee the branch or has this to be done by the maintainer)
- Not accepting a pull-request (see above)

**Comment by htgoebel** [comment]
More content:
- What happens if the pull-request is superseded by a new update before it was merged?

I thing I read this somewhere, but was not able to find at  https://pyup.io/docs/.

**Comment by Zac-HD** [comment]
> What happens if the pull-request is superseded by a new update before it was merged?

@pyup-bot closes the superseded pull and opens a new one.  [Here's an example.](HypothesisWorks/hypothesis-python/pull/912)

**Comment by rafaelpivato** [comment]
That's correct. PyUp should close superseded pull requests. You can change that behavior with **close_prs** setting.

https://pyup.io/docs/bot/config/#close-stale-prs
