### ISSUE TITLE
Display "N/A" in Python 3 status for packages not meant to be for Python 3

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#247]
Hi!

There are some packages that are only intended for use with Python 2, for example backports of Python 3 features (`futures`, `functools32`, `enum34`). For these packages we list them in our requirements file using conditional syntax, like so:
```
futures==3.1.1; python_version < '3' \
    --hash=sha256:c4884a65654a7c45435063e14ae85280eb1f111d94e542396717ba9828c4337f \
    --hash=sha256:51ecb45f0add83c806c68e4b06106f90db260585b25ef2abfcda0bd95c0132fd
```

Currently these packages display on https://pyup.io/repos/github/mozilla/treeherder/ as "PY3 :x:" and are included in the "Python 3 blockers" count, when they aren't blocking our Python 3 migration. Ideally this would instead be "PY3: N/A" and for them not to be included in the count.

It seems that possible solutions for this are:
1) Embed a whitelist of packages that should be excluded into pyup
2) Honour the `python_version < '3'` style syntax (though unless there's an easy way to make use of pip / pkg_resources's parser, this might get complicated to support all variations)
3) Add an additional pyup-specific Python 3 ignore syntax that people can add to their requirements file to indicate that the package should be excluded

Thoughts? :-)

**Comment by edmorley** [comment]
If it helps, caniusepython3 uses approach (1), and also offers alternatives for packages that have a Python 3 fork:
https://github.com/brettcannon/caniusepython3/blob/823233b6323f6878c971e2ec1a7fd4e6fa67fb2c/caniusepython3/dependencies.py#L70-L74
https://github.com/brettcannon/caniusepython3/blob/823233b6323f6878c971e2ec1a7fd4e6fa67fb2c/caniusepython3/overrides.json

**Comment by jayfk** [comment]
I think adding a whitelist is the best option. Probably just use the one from caniusepython3 👍

**Comment by rafaelpivato** [comment]
Let me know if you are still using Python 2.7 whether do you still suffer from this, please.
