### ISSUE TITLE
Patch==1.16 Returns Wrong Version To Update

### ISSUE THREAD

**Issue by jeffshek** [pyupio/pyup#248]
![image](https://user-images.githubusercontent.com/392678/31304858-229f2c74-aafa-11e7-8c6a-5019050d7d77.png)

https://pypi.python.org/pypi/patch - The latest is 1.16. I'm able to get around this easily, you guys are seriously amazing.

**Comment by jayfk** [comment]
Hey @jeffshek!

Looks like this is also wrong on PyPi: https://pypi.python.org/pypi/patch/json

```
...
        "version": "10.04", 
...
"10.04": []
```

**Comment by jayfk** [comment]
Thanks for reporting. Merging this issue into #252
