### ISSUE TITLE
django-bootstrap4 - v0.0.3 tries to update to non-existent 0.1 version

### ISSUE THREAD

**Issue by nikolas** [pyupio/pyup#251]
Version 0.1 doesn't seem to exist: https://pypi.python.org/pypi/django-bootstrap4/0.1

But pyup is trying to update to it: https://github.com/ccnmtl/econplayground/pull/67

**Comment by jayfk** [comment]
Looks like this is also wrong PyPi: https://pypi.python.org/pypi/django-bootstrap4/0.1/json

```
...
        "version": "0.1", 
...
"releases": {
        "0.1": [],
```

**Comment by jayfk** [comment]
Thanks for reporting. Merging this issue into https://github.com/pyupio/pyup/issues/252

**Comment by FEW162626** [comment]
i didn't create this
