### ISSUE TITLE
Inconsistent 'outdated' status for packages marked with 'pyup' annotations

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#253]
Hi!

In our requirements file ([here](https://github.com/mozilla/treeherder/blob/f0940ec37d36de08e8a067f8d1778ab008bb5de0/requirements/common.txt#L0)), we have several packages that have `# pyup:` annotations pinning them to an older range:
```
celery==3.1.25 \
    --hash=sha256:1954a224805f3835e5b6f5998ec9fe51db3413cc49e59fc720d314c7913427cf \
    --hash=sha256:6ced63033bc663e60c992564954dbb5c84c43899f7f1a04b739957350f6b55f3  # pyup: <4 # Bug 1337717

kombu==3.0.37 --hash=sha256:7ceab743e3e974f3e5736082e8cc514c009e254e646d6167342e0e192aee81a6 # pyup: <4 # Bug 1337717

billiard==3.3.0.23 --hash=sha256:692a2a5a55ee39a42bcb7557930e2541da85df9ea81c6e24827f63b80cd39d0b # pyup: <3.4 # Bug 1337717

amqp==1.4.9 --hash=sha256:e0ed0ce6b8ffe5690a2e856c7908dc557e0e605283d6885dd1361d79f2928908 # pyup: <2 # Bug 1337717
```

All four of those packages have newer versions that are outside the pinned range (we had issues previously upgrading to celery 4, and it requires the older versions of all the other packages too):
https://pypi.python.org/pypi/celery
https://pypi.python.org/pypi/kombu
https://pypi.python.org/pypi/billiard
https://pypi.python.org/pypi/amqp

The pyup PR bot seems happy with this, since it hasn't opened up PRs for new versions.

However on the website (https://pyup.io/repos/github/mozilla/treeherder/) the status badges display like so:
* celery: outdated
* kombu: up-to-date
* billiard: up-to-date
* amqp: up-to-date

It seems like:
a) All of the statuses for those packages should be the same (whatever that may be), given they are all outdated and annotated in the requirements file
b) That perhaps there needs to be a third status of "outdated but ignored/pinned" (or whatever the more succinct wording of that is), to make it easy to see what the actionable items are when looking at the site

Many thanks :-)

**Comment by edmorley** [comment]
Is the bot and the site using a different requirements file parser perhaps, and the site one not accounting for the newlines?

**Comment by jayfk** [comment]
> Is the bot and the site using a different requirements file parser perhaps, and the site one not accounting for the newlines?

This! The parser on the site was more or less a demo to try it out without giving away authorization keys to Github. Now that people actually use it for their projects I'll need to make it a first class citizen.

> That perhaps there needs to be a third status of "outdated but ignored/pinned" (or whatever the more succinct wording of that is), to make it easy to see what the actionable items are when looking at the site

Yep, that's needed. Probably even a fourth of "outdated but on the latest release of a still supported train". For example, if you are using the latest Django 1.10.x release: You want to know that there's 1.11.x available but you are safe because you are using the latest 1.10 release which is not EOL.

**Comment by rafaelpivato** [comment]
Another issue relating to how we use (or are not using) **pyupio/dparse** properly and uniformly across all projects.
