### ISSUE TITLE
Package names on website all link to line zero of the requirements file

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#254]
**STR:**
1. Visit https://pyup.io/repos/github/mozilla/treeherder/
2. Click any of the package names shown under the `requirements/common.txt` heading

**Expected:**
That the package name links to something specific to that package, eg either the exact line in the requirements file, or else perhaps even more useful the PyPI page.

**Actual:**
Every package name links to line zero of the requirements file, eg:
https://github.com/mozilla/treeherder/blob/master/requirements/common.txt#L0

**Comment by jayfk** [comment]
Thanks @edmorley. Tracking this one here: https://github.com/pyupio/dparse/issues/7
