### ISSUE TITLE
Report broken or invalid config files instead of ignoring errors

### ISSUE THREAD

**Issue by Zac-HD** [pyupio/pyup#255]
In HypothesisWorks/hypothesis-python#938, we discovered that our `.pyup.yml` had been broken and silently ignored for six months.  While it's nice that the default behaviour is good, silent errors are terrible!

It would be great if @pyup-bot could open an issue on the repo when an invalid configuration file is detected, or even just email the maintainer.  Ideally this would validate both the file format and the config schema, and include tips on how to fix it.

**Comment by jason-neal** [comment]
I agree. I had capitalized the day of the week in  `schedule:`, which stopped pyup running at all for a couple of months.

**Comment by jayfk** [comment]
The bot will now open issues if there's an error with the config file: https://github.com/pyupio/pyup/commit/4c647be9e817b2dd4f3f870264ee1701c6a26e79
