### ISSUE TITLE
Support scheduling/delaying PRs without batching them up

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#262]
Hi!

pyup currently has a `schedule` config option ([docs](https://pyup.io/docs/bot/config/#schedules)), which allows for the batching up of updates into one periodic PR.

This has the following advantages:
1. Fewer email/IRC/... "PR opened" notifications.
2. Fewer CI jobs being triggered, so reduced impact on CI load.
3. Allows for scheduling the PR at a time when developers are not working, so:
    - impact on CI load is a non-issue
    - email/IRC/... notifications are less annoying (since they are seen in one go, once back online, rather than drip-feed)
    - by the time the notification is seen, CI will have already completed (compared to normal, when one sees the email, opens the PR but then can't merge straight away and has to remember to come back to it later).
4. Increases the chance that all of the necessary sdist/wheel uploads have occurred (working around #250).
5. Reduces churn (and risk) from breakages/hotfix updates (for example a major issue is spotted and a hotfix released N minutes/hours after), since the PR will just skip the intermediate broken versions.

However for us, having the updates in a single PR isn't ideal, since:
* if the Travis run fails, it's not clear which of the batched updates broke things.
* if one of the updates is broken, or if we want to stagger "riskier" updates, it requires manual intervention to just land a subset of the updates.

If it were possible to schedule the PRs but not have them batched up into one (ie multiple PRs opened at once), it would still provide advantages 3-5 above, and in fact 1 and 2 would also be less of an issue due to 3.

Alternatively, the ability to just delay the individual PRs by N hours after the package was updated (rather than on a fixed schedule) would still provide advantages 4 and 5, even though it wouldn't help with the others.

Many thanks :-)

**Comment by nnadeau** [comment]
I'd also appreciate non-batched, scheduled PRs. Given the following case:
![image](https://user-images.githubusercontent.com/6395915/35812608-7ce3babe-0a5f-11e8-8955-8ce0ab0ef080.png)

- I know `hypothesis` is currently blocking this PR
- But I want to merge the other updates...
- Only solution is to modify the PR, reverting the bad update
