### ISSUE TITLE
LTS

### ISSUE THREAD

**Issue by SillyInventor** [pyupio/pyup#263]
We're using Django, and they've updated to 2.0, but there is LTS for 1.11 until April 2020. We plan on using that (our libraries are not all up). Is there a way to specify that we want updates less than x.x - expiring on some date? If not, I request that feature.

**Comment by jayfk** [comment]
There's currently no way to do this but I really like that feature.

**Comment by kairichard** [comment]
This is somewhat related -> https://github.com/pyupio/pyup/issues/277

**Comment by SillyInventor** [comment]
Not sure if this is the kind of thing you'd like / need help on, should I lend you a hand with this?

**Comment by jayfk** [comment]
> Not sure if this is the kind of thing you'd like / need help on, should I lend you a hand with this?

The main problem is that we need some way to tell the bot what an LTS release is and update it accordingly. There's no way to do this through PyPi.

We could add it to the bot itself but that would require keeping the bot up-to-date for those using the CLI.

Adding it to the online service is probably the easiest thing but not a solution for the people using the CLI.

**Comment by SillyInventor** [comment]
How about putting it either in a config or a comment in the requirements?

**Comment by jayfk** [comment]
I now realize you wrote this in your original comment, that’s a great idea 👍🏼

**Comment by jayfk** [comment]
It's now possible to set an expiry date by appending `until YYYY-MM-DD` to the filter.

**Example**
```
Django==1.7.6 # pyup: < 1.7.8 until 2018-05-22
```
