### ISSUE TITLE
"Scheduled weekly dependency update for week 00"

### ISSUE THREAD

**Issue by Zac-HD** [pyupio/pyup#265]
HypothesisWorks/hypothesis-python#1053

It looks like week counts are limited to two digits.

**Comment by jayfk** [comment]
Looks like an off by one error to me 🤣 

I believe Python begins to count each years weeks by 0, instead of 1 as humans do.

**Comment by Zac-HD** [comment]
Ah, that makes sense 😄 

How about labelling the pull by date instead of week number?  If I'm searching for a change "Scheduled weekly dependency update for 2018-01-26" still tells me the update frequency, but now also the date on which these dependencies were current.
