### ISSUE TITLE
msgpack-python has been renamed msgpack

### ISSUE THREAD

**Issue by fake-name** [pyupio/pyup#266]
Basically the title.

It appears that the `msgpack` people have decided to rename their package for purely cosmetic reasons, breaking lots of things in the process.

See https://pypi.python.org/pypi/msgpack/0.5.1

It'd be nice if pyup replaced one dependency with the other, since apparently the only actual change is the name.

**Comment by jayfk** [comment]
Whelp, that sucks!

I can understand the frustration, but I think that's not something that pyup should handle. 

Renaming the package locally is a find & replace that's completed in a couple of minutes. Telling the bot to do that involves rewriting regexes, adding a new template, adding a new task, a couple of logic changes, tests, waiting for CI, a new deployment and finally monitoring.

**Comment by fake-name** [comment]
Ok, cool, I wasn't sure how general pyup was trying to be.
