### ISSUE TITLE
Document comments in requirements file

### ISSUE THREAD

**Issue by browniebroke** [pyupio/pyup#267]
While browsing pydanny's cookie-cutter template for Django project, I realised it was possible to tell pyup to [skip a specific version](https://github.com/pydanny/cookiecutter-django/blob/44e90477a5e26e339fa7d1e851dec71dc81c59b9/requirements.txt#L2) or to [avoid upgrading to the next major one](https://github.com/pydanny/cookiecutter-django/blob/44e90477a5e26e339fa7d1e851dec71dc81c59b9/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt#L9) using inline comments in the requirements.txt.

I looked it up in the documentation, but I couldn't find any mention of it. I wanted to contribute and help to update the documentation but it seems to be maintained outside of this code base. Is there any way I can help documenting this? It would be helpful to get a mention of this feature somewhere.

**Comment by jayfk** [comment]
Hey @browniebroke!

I'm afraid that the documentation is currently in pyup.io's codebase (the only thing that isn't open source). But, the filter you mentioned is documented here: https://pyup.io/docs/bot/filter/

**Comment by browniebroke** [comment]
Right! Sorry if I missed that, and thank you for updating if that's new!
