### ISSUE TITLE
Dates on monthly pull requests are in american format!!!

### ISSUE THREAD

**Issue by samuelcolvin** [pyupio/pyup#271]
Just noticed dates in branch names are in american format eg. `pyup-scheduled-update-02-01-2018`.

This happens when `schedule: 'every month'` is in `.pyup.yml`.

This is mad:
* american dates formats are mad
* they're strongly discouraged in most computer related specs
* they're very ambiguous
* they make tab completion when checking out a branch much more difficult

Please use `YYY-MM-DD` eg.`2018-02-01`. This is both not ambiguous and makes finding the right branch easier with tab completion.

Sorry to use the word "mad", I'm a big fan of pyup, but this does seem like a genuinely "wrong" option.

**Comment by jayfk** [comment]
> american dates formats are mad

Totally agreed. I have no idea how they ended up here.

Thanks for the PR!
