### ISSUE TITLE
Add option for commit message template

### ISSUE THREAD

**Issue by htgoebel** [pyupio/pyup#274]
The commit messages generated by pyup do not match the commit message requirements for one of my projects. Please add an option to specify the commit message. e.g.
```
# Configure the commit message template
# default: "Update ${packagename} from ${old_version} to ${new_version}"
# allowed variables: packagename, old_version, new_version
commit_message_template: "Requirements: Push ${packagename} to ${new_version}"
```

**Comment by kevinkjt2000** [comment]
Having this feature would certainly help when it comes to automated semantic versioning.

**Comment by martinm82** [comment]
Would be really great as right now the integration with the semantic pull requests app is causing problems due to wrong PR titles.

https://github.com/apps/semantic-pull-requests

**Comment by rafaelpivato** [comment]
This should be available with next release thanks to @Kaligule

**Comment by Kaligule** [comment]
@rafaelpivato Very cool, glad to have helped. Do you know when that release might happen?

**Comment by rafaelpivato** [comment]
In the next few days we should be releasing.

**Comment by Kaligule** [comment]
@rafaelpivato Any updates on the release? It has been over a month now.

**Comment by rafaelpivato** [comment]
Thanks for the heads-up, @Kaligule 

Just released version 1.1.2

**Comment by Kaligule** [comment]
@rafaelpivato Thanks :) Can you point me to a place where I can update the documentation about this new feature? As mentioned in the [pull request](https://github.com/pyupio/pyup/pull/389):

> I would like to document the new options, but I couldn't find the place to do it other then commit-message and PR-description.

**Comment by rafaelpivato** [comment]
At this moment the README is the best place as RTD build is pretty outdated.
