### ISSUE TITLE
Improve Gitlab Integration

### ISSUE THREAD

**Issue by kairichard** [pyupio/pyup#276]
Hi @jayfk  and @samdroid-apps 
Thank you for providing a Gitlab integration in the first place we are total fans. 
The question I have is whether you accept changes to it. 

Case in point would be a flag to allow Gitlab to `merge_when_pipeline_succeeds` and another flag for `should_remove_source_branch`. We currently have a custom made script that does exactly that because we don't want to manually merge changes that pass all tests.

The problem here would be that these changes are somewhat specific to Gitlab.  I could imagine an `os.env` kind of flag.  Let me know what you think. 

Thanks,
Kai

**Comment by jayfk** [comment]
How does this work exactly? Is this just a flag you set via API calls, or is this something the bot needs to monitor?

I could imagine that passing the config dict to the function that opens the pull request would be enough to accomplish this (if this is configurable via the API). The code parts that are specific for gitlab could then pick this up and set the flags accordingly.

---

As an aside, I'm a huge fan of gitlab and I'm still considering to add it as a first class citizen to the online service. There wasn't that much demand for it but if there are enough people interested in this (where some of them pay for private/org repos), I'd love to do that.

If you know anyone, please send them here or tell them to nag me at ```jay@pyup.io```.

**Comment by jayfk** [comment]
> Thanks for responding - we bought an api key in the meantime.

That's great, thanks!

> With the config I assume you mean .pyup.yml, right? How about a gitlab section:

That's exactly what I had in mind. 

I don't know when I have the time to get around doing this, though. Lots of big feature branches I currently need to work on :/.

**Comment by kairichard** [comment]
@jayfk if you don't mind we can take a shot at it as we have a lot of work already done. What do you think?

**Comment by jayfk** [comment]
@kairichard Sure, go ahead. 

You probably just need to 

- add the parameters to the config file
- pass the config to the create pull request call here: https://github.com/pyupio/pyup/blob/master/pyup/bot.py#L418-L423
- update the gitlab integration
- update the parameters the github integration takes

You probably knew all this already, but I've found that the bot code becomes pretty hard to navigate if you are not familiar with the code base.
