### ISSUE TITLE
Allow to specify minimum next version to update to

### ISSUE THREAD

**Issue by belugame** [pyupio/pyup#277]
We use the packages `boto3` and `botocore` which have new minor versions released at least once a week. These minor updates are not crucial for us. Though they create some work every week to merge. As their lines are above each other in the requirements file, they always create a conflict to be resolved manually.

It would be nice to have a feature to tell pyup to ignore minor version jumps for a certain package. E.g. when you are on 1.0.15 do not update until there is a 1.1.x.

Not sure about a smart syntax though. `>=` would be the closest but is of course used for a different meaning.
Maybe:

`boto3==1.0.15  # pyup: min 1.1.0`

@kairichard FYI

**Comment by jayfk** [comment]
Yes, that's indeed a much needed feature. I'm getting annoyed by all these boto updates myself.

**Comment by jayfk** [comment]
If the package follows semantic versioning, the best thing would be to update based on `major`, `minor`, `patch`. 

```boto==1.2.3 # pyup: update major``` would update to 2, not 1.2 and not 1.2.4
```boto==1.2.3 # pyup: update minor``` would update to 2, 1.3 but not 1.2.4
```boto==1.2.3 # pyup: update patch``` would take all updates, except something like 1.2.3.dev2

**Comment by jayfk** [comment]
This should work exactly as in the example above.

**Comment by belugame** [comment]
Awesome, thank you for the rapid implementation!
