### ISSUE TITLE
Add a non-verbose pull request template

### ISSUE THREAD

**Issue by jayfk** [pyupio/pyup#278]
As requested by @gvanrossum, add a template that's less verbose and less human.

```
Updates {package} from {old} to {new}.

{changelog_url} | {pypi_url} | {repo_url}
```

**Comment by jayfk** [comment]
This is now the default + changelogs are now collapsed, making them easier to read.

<img width="444" alt="screen shot 2018-03-07 at 11 27 31" src="https://user-images.githubusercontent.com/2930472/37088527-f2f92cb0-21fd-11e8-98f5-66686a302d91.png">

**Comment by The-Compiler** [comment]
Just noticed this, and I really like it - makes things much more readable IMHO :+1:
