### ISSUE TITLE
Branch created initially with no new commits

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#280]
Hi!

It seems that pyup first creates and pushes a new branch that's equal to master, and then only after pushes changes to it. This causes Travis to trigger jobs on the first push, even though it doesn't yet have changes. 

For example:

mozilla/treeherder/pull/3317
-> https://screenshots.firefox.com/9mQlhzMxPjcStcDg/travis-ci.org

mozilla/treeherder/pull/3321
-> https://screenshots.firefox.com/gBzUSwfM8uyIS60a/travis-ci.org

Please can pyup only push once, with the actual commits?

**Comment by jayfk** [comment]
Haven't found a way to do this, yet. The bot is using the GitHub API to create the branch: https://github.com/pyupio/pyup/blob/master/pyup/providers/github.py#L116

Any idea how to do this without pushing the branch?

**Comment by edmorley** [comment]
Could the commits be pushed before creating the ref?
If not perhaps a feature request could be filed against the github NPM package for a way to handle this?

Alternatively perhaps an NPM package for interacting with github using the git protocols might work?

**Comment by jayfk** [comment]
This is all Python code on PyPi, no NPM involved :)

While going over GitHubs API docs I wasn't able to find an obvious way to do this. Going to contact support next.

**Comment by edmorley** [comment]
> This is all Python code on PyPi, no NPM involved :)

Sorry I've been filing a number of issues against https://github.com/renovateapp/renovate recently; crossed mental streams :-)

**Comment by rafaelpivato** [comment]
Duplicated by #331
