### ISSUE TITLE
pyup bot doesn't resolve PR conflicts

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#289]
Hi!

This PR is now showing as having conflicts in the requirements file, since another pyup PR was merged that changed lines near to those being updated:
https://github.com/mozilla/treeherder/pull/3404

However the PR hasn't been updated by the bot to resolve the conflicts, similar to how [Renovate](https://renovateapp.com/) does.

Rather than trying to rebase/resolve conflicts, the simplest way would presumably be for pyup to just reapply the package update to master and then force push to the branch for the PR.

Many thanks :-)

**Comment by marco-c** [comment]
It's strange that the Travis builds for the outdated PRs are canceled though, so you can't see if they would eventually pass or not.
```
This job was cancelled because the "Auto Cancellation" feature is currently enabled, and a more recent build (#267) for branch pyup-update-taskcluster-4.0.0-to-4.0.1 came in while this job was waiting to be processed.
```
