### ISSUE TITLE
Multidict 4.3.1 is out, pyup shows only 4.3.0

### ISSUE THREAD

**Issue by Callek** [pyupio/pyup#299]
![image](https://user-images.githubusercontent.com/1415602/40066171-8c808612-5831-11e8-8412-b981e9ad41a6.png)

![image](https://user-images.githubusercontent.com/1415602/40066202-9c4ab05e-5831-11e8-86b7-a06e412ecff3.png) (from http://multidict.readthedocs.io/en/latest/changes.html )

And then pypi itself shows 4.3.1 out days ago:
![image](https://user-images.githubusercontent.com/1415602/40066254-b9b04118-5831-11e8-9e16-7e0685ee6931.png)

**Comment by webknjaz** [comment]
It's probably related to inconsistent publishing of dists from separate CI/CD jobs:
* pypa/warehouse#4056
* aio-libs/multidict#182
* aio-libs/aiohttp#2347

**Comment by rafaelpivato** [comment]
@Callek are you still suffering from this specific issue? If so, can you share your command line call using `--log-level DEBUG`?

**Comment by Callek** [comment]
Sorry for the late reply, I'm no longer at an org that is using Pyup so I'm going to close this.
