### ISSUE TITLE
How to batch PRs every few days

### ISSUE THREAD

**Issue by pzelnip** [pyupio/pyup#300]
What I want is pyup to do a single PR with all updates every Sunday, Wednesday, and Friday.  I tried putting this in [my .pyup.yml](https://github.com/pzelnip/www.codependentcodr.com/blob/master/.pyup.yml):

```
update: all

schedule: "every sunday, wednesday, friday"
```

Yet I still had two separate PR's opened yesterday (Tuesday) for ```awscli``` and ```boto3```.   How can one configure pyup to do a batch PR, and check on a periodic (every few days) schedule?  The docs (https://pyup.io/docs/usage-examples/) don't seem to have this case as an example, so I'm unsure if I have the syntax wrong, or if it's unsupported.

**Comment by rafaelpivato** [comment]
It would be lovely to have something like that, but we don't support it at this moment.

In case you are curious, here is the REGEX for parsing the schedule: https://github.com/pyupio/pyup/blob/56a3fb660e9676393461a44397cee877d34c7288/pyup/config.py#L11-L21

And here is the documentation for schedules: https://pyup.io/docs/bot/config/#schedules
