### ISSUE TITLE
Skip certain packages

### ISSUE THREAD

**Issue by ChiKenNeg** [pyupio/pyup#302]
Is there a way for PyUp to ignore a list of packages? 

there are no traces of skipping package updates in the docs.

**Comment by luzfcb** [comment]
ignore:

```
flask # pyup: ignore
```

limit version
```
django==2.0.6  # pyup: < 2.1

```

https://pyup.io/docs/bot/filter/

**Comment by ChiKenNeg** [comment]
Thanks!
