### ISSUE TITLE
URL in changelog broken by issue number redaction

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#310]
Hi

In this PR:
mozilla/treeherder#3784

The changelog section contains this URL:
`https://django-filter.readthedocs.io/en/master/guide/migration.htmlmigrating-to-2-0`

Whereas the actual URL in the original changelog is:
`https://django-filter.readthedocs.io/en/master/guide/migration.html#migrating-to-2-0`

I'm presuming the `#` was removed by the process that sanitizes the GitHub issue numbers (ie converts `#123` to `123`).

Please could the regex be tightened up, to avoid false positives?

**Comment by Jwomers** [comment]
@edmorley Got it, thanks.

**Comment by Jwomers** [comment]
@edmorley tracked this down to our open source changelogs repo: https://github.com/pyupio/changelogs/blob/0cdb929ac4546c766cd7eef9ae4eb4baaa08f452/changelogs/parser.py#L35

I should get to this in the next few days. 

cc @jayfk for context.

**Comment by Jwomers** [comment]
@edmorley I have created a PR with a fix here: https://github.com/pyupio/changelogs/pull/139/files

@jayfk did you want to strip #'s from GitHub issue numbers? If so, I can update the regex accordingly.

**Comment by Jwomers** [comment]
@jayfk got it, so I will add a regex to replace`#[0-9]*` with `[0-9]*` 👍

**Comment by rafaelpivato** [comment]
Thanks for all information shared, guys. Fixed with https://github.com/pyupio/changelogs/pull/139

Should be available with next release to PyPi.
