### ISSUE TITLE
Problems with non-GitHub setups (e.g., GitLab); --bot-token option undocumented

### ISSUE THREAD

**Issue by MartinFalatic** [pyupio/pyup#311]
On a GitLab configuration, if `--bot-token <token>` isn't specified, stale PRs/MRs will not be closed:

https://github.com/pyupio/pyup/blob/2bed5ce0e02f55f7d4ff03c08270bb0ecabcf1b2/pyup/bot.py#L232

The bot-token option isn't well-documented, and I don't see any documentation indicating it's necessary for this behavior to work (though clearly it should be).

**Comment by MartinFalatic** [comment]
Even with bot-token set, pyup doesn't seem to be closing MRs. Is this a known issue for the GitLab use case?

**Comment by MartinFalatic** [comment]
Apparently GitLab support isn't really present, so I made the changes required to enable it.

#314

**Comment by rafaelpivato** [comment]
Closing this as the underlying issue was fixed by the reporter himself with a contribution. Thanks for that.
