### ISSUE TITLE
pyup is opening one PR to update multiple dependencies

### ISSUE THREAD

**Issue by marco-c** [pyupio/pyup#317]
https://github.com/mozilla/coverage-crawler/pull/117 says:
> Subsequent pull requests will update one dependency at a time, each in their own branch. If you want to start with that right away, simply close this PR.

So I closed the PR, but pyup opened https://github.com/mozilla/coverage-crawler/pull/118, updating again both dependencies.

**Comment by Jwomers** [comment]
Hi @marco-c - it looks like your .pyup.yml file specifies a weekly schedule which is likely causing this to happen. This means PyUp will bundle all updates into a single PR once a week. The copy:
> Subsequent pull requests will update one dependency at a time, each in their own branch
Isn't correct if you have a schedule set.

>

**Comment by marco-c** [comment]
Oh, I see. So to get one PR per dependency update I simply need to remove the schedule?

**Comment by Jwomers** [comment]
@marco-c yes that should work. If it doesn't let me know and I can help debug!
