### ISSUE TITLE
pyup continually recreating branch for non-existent package version

### ISSUE THREAD

**Issue by edmorley** [pyupio/pyup#323]
Our current simplejson dependency is on 3.16.0, which is a valid version.
However pyup keeps on creating a new branch for 3.16.1, which was actually unpublished.
I'm presuming a pyup cache somewhere needs clearing?

See:
https://github.com/mozilla/treeherder/tree/pyup-update-simplejson-3.16.0-to-3.16.1

Note: This issue is related to, but not the same as #308. That issue is about pyup knowing how to downgrade if a package later becomes unpublished. This issue is about not falsely trying to **upgrade** when the package has been unpublished.

**Comment by Jwomers** [comment]
@edmorley I've update this. Thanks for your patience. I'm also working on a system to clear our cache every few hours so this doesn't continue to happen.

**Comment by edmorley** [comment]
I've deleted the simplejson branch and it's not re-appeared. Many thanks :-)
