### ISSUE TITLE
Old pull requests being closed for ignored packages

### ISSUE THREAD

**Issue by nthomas-mozilla** [pyupio/pyup#325]
We're using the pyup bot, configured to [ignore pycodestyle](https://github.com/mozilla/balrog/blob/7ff88bb/requirements-test.txt#L42) because v2.4.0's incompatibility with the latest flake8 (#290), update on a weekly schedule, and the default value of closing old PRs.

For the last two weeks the [scheduled update](https://github.com/mozilla/balrog/pull/830) has properly ignored pycodestyle but still closed the [old PR](https://github.com/mozilla/balrog/pull/540). This is undesirable because we're leaving the PR open to track updating once flake8 eventually does a release. It seems like the `ignore` is not being taken into account when considering `close_prs`.

**Comment by rafaelpivato** [comment]
Interesting use case. My understanding is that ignoring should be a way to get rid of unpleasant fixes/changes about an specific package or vulnerability. Changing the way you asked might cause unintended behavior to other users IMHO.

Closing this based on that. Let me know if you have other thoughts.
