### ISSUE TITLE
Please upload v1.0.3 to PyPI

### ISSUE THREAD

**Issue by jonesnc** [pyupio/pyup#336]
It looks like `1.0.3` has not been uploaded to PyPI yet -- [`1.0.2`](https://pypi.org/project/pyupio/) is the latest version that PyPI is aware of.

**Comment by Jwomers** [comment]
@jonesnc yes correct, coming soon!

**Comment by rafaelpivato** [comment]
Closing this as version 1.1.0 is the latest now at PyPi. Thanks for the report.
