### ISSUE TITLE
"Unknown error" on pyup repository

### ISSUE THREAD

**Issue by nikolas** [pyupio/pyup#347]
I'm trying to administer one of my repos on Pyup, and I'm seeing this "Unknown Error" notice. Can you look into it?

![2019-04-23-110013_1045x799_scrot](https://user-images.githubusercontent.com/59292/56591563-fa577680-65b6-11e9-9f30-9e6ec736d01b.png)

**Comment by nikolas** [comment]
This seems to happen if the github repo is archived. So it's a minor thing, but Pyup could at least show that it's archived rather than having an Unknown error.

**Comment by cooperlees** [comment]
I opened a separate issue on getting same error - My repo is not archived.

**Comment by nikolas** [comment]
@cooperlees yeah, I'm now getting this error for all my repositories, even those that aren't archived,

**Comment by rafaelpivato** [comment]
@cooperlees we made some changes related to this one month ago. 

Are you still getting this?

**Comment by cooperlees** [comment]
https://pyup.io/account/repos/github/pypa/bandersnatch/ Is working - I went through many revision of the .yml to get it to work again.

Are standards compliant YAML files now supported?

**Comment by rafaelpivato** [comment]
YAML handling is not as good as I would like, specially for warnings. I'm keeping this open if there is no duplicate in regards to that.

**Comment by rafaelpivato** [comment]
Duplicatest #346 and #292
