### ISSUE TITLE
Pyup constantly loading requirements in website

### ISSUE THREAD

**Issue by AaronBlare** [pyupio/pyup#352]
A week ago pyup stopped creating PRs with updates.
When I go to website, I can only see loading of requirements list, and it has never finished - just always loading.
https://pyup.io/repos/github/AaronBlare/pydnameth/
Webhook on Github returns Runtime error.

I didn't change my pyup.yml file: https://github.com/AaronBlare/pydnameth/blob/master/.pyup.yml

What an be the reason and how can I fix it?

**Comment by Harmon758** [comment]
I'm encountering the same issue.
I've contacted support@pyup.io, but no response yet.

**Comment by AaronBlare** [comment]
@Harmon758 I have already moved from pyup to dependabot - it is supported better now

**Comment by bmjjr** [comment]
I've used the service for a few years and it hasn't changed much. Seems totally unmaintained now, with 500s showing all the time. Whoever is running it now should at least give an update what is going on.

**Comment by Harmon758** [comment]
The issues seem to have been resolved now.
Some backlogged PRs weren't retroactively made, but deleting the respective branches that were created retriggered them to be remade with corresponding PRs.
Reloading the repository through the website was resulting in a "Unknown Error", but that seems to be fixed as well now.
