### ISSUE TITLE
pyup stopped working on mozilla/bugbug repository

### ISSUE THREAD

**Issue by marco-c** [pyupio/pyup#353]
It used to work, then at some point I stopped receiving PRs.
The repo page on pyup.io never ends loading.

**Comment by nikolas** [comment]
Same problem here.. I have many repos set up with pyup that haven't been getting updates for the past few weeks.

**Comment by Harmon758** [comment]
Duplicate of #352.
I've contacted support@pyup.io, but still no response.
The entire site at https://pyup.io/ now returns a 500 Internal Server Error.
