### ISSUE TITLE
setuptools 41.1.0.post1 deleted but pyup still trying to update

### ISSUE THREAD

**Issue by cooperlees** [pyupio/pyup#357]
Even tho I guess the version 41.1.0.post1 has been deleted upstream, it seems PyUP still thinks it's available.

I closed a PR saying it was deleted and straight away it was opened again:
https://github.com/pypa/bandersnatch/pull/302

Is there some missing invalidation pipeline?

**Comment by rafaelpivato** [comment]
Looks like a bug in the algorithm deciding next update version. `post` prefix was not even supposed to be considered, IMHO.

**Comment by cooperlees** [comment]
Post is a valid version - It’s defined here in PEP440: https://www.python.org/dev/peps/pep-0440/#post-releases

**Comment by rafaelpivato** [comment]
I think we need then to increase this range. My understanding before looking at your link was that any alpha character after the version would indicate a "pre-release" or something.

Thanks for pointing that out. Well, so it looks like the behavior deciding which version to pick was somewhat correct. This apparently duplicates #308 then.
