### ISSUE TITLE
PyUp opens PR using wrong version

### ISSUE THREAD

**Issue by duckinator** [pyupio/pyup#363]
I managed to get a PR from PyUp to update to the _second-newest version_, today.

1. https://github.com/duckinator/bork was using pep517 v0.5.0, which was actually version out-of-date, but never corrected by PyUp because I'd explicitly pinned it.
2. At 7:30AM EST today (2019-09-27 07:30 EST), v0.7.0 of the pep517 library was released.
3. At 7:33AM EST today (2019-09-27 07:33 EST), PyUp opened https://github.com/duckinator/bork/pull/35, to update pep517 to v0.6.0, which was released over a month ago.

My suspicion is that there's probably a cache involved, somewhere, but I have nothing concrete to back that up.

**Comment by rafaelpivato** [comment]
Good thing you did report this, @duckinator 

Were you using an API key or the public **pyupio/safety-db** database?

The point is that the public database gets updated once a month, so that behavior would be expected.

**Comment by duckinator** [comment]
I enabled https://pyup.io/ for my repo. So I'm assuming probably the public one?

**Comment by rafaelpivato** [comment]
My bad @duckinator -- that was not a Safety CI update. In that case, only PyPi store information is used. What I saw in the logs is that our bot commit was made on the same day of the release of version 0.7. So, maybe there was a race condition or a bug electing next version to be used. Hard to say now.

If you get that happening again, please let me know. I will try to check logs ASAP then.
