### ISSUE TITLE
.pyup.yml seems to be ignored for gitlab repos

### ISSUE THREAD

**Issue by bluespider42** [pyupio/pyup#370]
Config in .pyup.yml is ignored.
including label_prs, branch_prefix, close_prs
Is this supposed to work for gitlab as the documentation is very poor?

**Comment by rafaelpivato** [comment]
Some options are not apparently available [for GitLab yet](https://github.com/pyupio/pyup/blob/56a3fb660e9676393461a44397cee877d34c7288/pyup/config.py#L163) as opposed to [default GitHub](https://github.com/pyupio/pyup/blob/56a3fb660e9676393461a44397cee877d34c7288/pyup/config.py#L24) options.
