### ISSUE TITLE
GitLab merge bad HTTP request parsing of arguments

### ISSUE THREAD

**Issue by ferhat-aram** [pyupio/pyup#384]
When I tried to use the automatic merging, when the pipeline succeeds and after that deleting the source branch, I run into problems, as the HTTP request is not allowed. 

This issue relates to the library itself and I also already created an issue there [https://github.com/python-gitlab/python-gitlab/issues/1120](url). 

Nevertheless the problem would still remain here partly, when using the argument to remove the branch after a successful merge.

This is because the method references the wrong parameter for the option to remove the source branch afterwards, as you see here: 

```
pyup/pyup/providers/gitlab.py

    def _merge_merge_request(self, mr, config):
        mr.merge(remove_source_branch=config.gitlab.should_remove_source_branch,
                 merge_when_pipeline_succeeds=True)
```

Even though the methods accept this as a valid paramaeter because of **kwargs, this wouldn't parse the given argument correctly as a query_data (this is the issue in the python-gitlab library itself but will lead after the fix to issues here):  

```
gitlab/v4/objects.py

 def merge(
        self,
        merge_commit_message=None,
        should_remove_source_branch=False,
        merge_when_pipeline_succeeds=False,
        **kwargs
    ):

      path = "%s/%s/merge" % (self.manager.path, self.get_id())
        data = {}
        if merge_commit_message:
            data["merge_commit_message"] = merge_commit_message
        if should_remove_source_branch:
            data["should_remove_source_branch"] = True
        if merge_when_pipeline_succeeds:
            data["merge_when_pipeline_succeeds"] = True
        server_data = self.manager.gitlab.http_put(path, post_data=data, **kwargs) 
        self._update_attrs(server_data)
```

Here the arguments are currently parsed as "post_data", which is simply wrong in the python-gitlab library itself, as I already explained several times. After my pull request there would be accepted though, the argument wouldn't be handled as "should_remove_source_branch", but as a **kwargs, since the naming "remove_source_branch" is simply wrong. 

I'll do a pull request if you would allow me to do so, as I already fixed that locally.

**Comment by ferhat-aram** [comment]
The python-gitlab version should be updated to the latest version, as the fix for that problem [](https://github.com/python-gitlab/python-gitlab/pull/1121) will come with the latest version.

**Comment by rafaelpivato** [comment]
Let me know if this was not fixed with your PR. Thanks for all that work, @ferhat-aram !
