### ISSUE TITLE
Pyup.io is currently down?

### ISSUE THREAD

**Issue by pzelnip** [pyupio/pyup#400]
As the subject reads, https://pyup.io is  currently down.

![image](https://user-images.githubusercontent.com/414933/104484231-e408ff80-557d-11eb-94e1-5527e912113e.png)

**Comment by harlekeyn** [comment]
Thanks for the notification, Adam. We're experiencing a glitch indeed and the entire team is working on resolving it.

**Comment by harlekeyn** [comment]
We're back up, Adam!
