### ISSUE TITLE
Option to limit packages versions to ones supported by all Python versions?

### ISSUE THREAD

**Issue by bwoodsend** [pyupio/pyup#404]
Hello, I maintain a library which currently supports Pythons 3.6 to 3.9. We have a line in our requirements saying:
```
matplotlib==3.3.4
```
which is now bumped by pyup to 3.4.0 but ... matplotlib 3.4.0 dropped support for Python 3.6 so the requirements file is effectively rendered uninstallable on Python 3.6 and everything falls apart from there. This is becoming a bit of a habit.

In my mental Utopian image of pyup, I'd like to be able to able to specify:
```yaml
# .pyup.yml
python_versions:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
```
And pyup will check the `python_requires` constraints of each new version it recommends before recommending it.

C'est possible?

**Comment by harlekeyn** [comment]
Hello Brénainn. Thank you for this suggestion.

We actually already have something similar on our own _to do_ list so I will add a reference to your comments.

I do not expect this to be implemented soon…
