### ISSUE TITLE
pyupbot spam

### ISSUE THREAD

**Issue by techtonik** [pyupio/pyup#60]
@pyup-bot is too noizy creating and closing new issues. It will help if it could update it's own issues, and instead of "Update sphinx to 1.4.2 by pyup-bot" create "Autoupdate of sphinx [1.4.0 -> 1.4.2]" and update the header as new versions are coming out.

**Comment by jayfk** [comment]
It is meant to be so noisy. I don't think silently updating issues and pull requests is a good idea, because it's easy to miss an important update this way.

**Comment by techtonik** [comment]
If it adds comment to an old issue it won't be silent, and it will cut down amount of spam at 2+
