### ISSUE TITLE
Adding other requirement files

### ISSUE THREAD

**Issue by mimischi** [pyupio/pyup#68]
Have you thought about adding other non-django requirement files into the pyup check? Most specifically I'm talking about the requirements file provided by [hitchtest](https://github.com/hitchtest/hitch), which is found in "<project root>/hitch/hitchreqs.txt".

Maybe an option to define other folders/files within the project would do the job!

**Comment by jayfk** [comment]
Support for a config file just arrived, documentation is on its way. 

In the meantime, this should work:

Create a file called `.pyup.yml` in the project root of your repository

```
requirements:
  - hitch/hitchreqs.txt
```

**Comment by mimischi** [comment]
Thanks, but this does not seem to work for me though. Added a file just like this, but refreshing my repository at pyup.io does not add the new file.

**Comment by jayfk** [comment]
Just had a look at it. The file is in `tests/hitchreqs.txt` instead of `hitch/hichtreqs.txt`.

This should do the trick:
```
requirements:
  - tests/hitchreqs.txt
```

Another thing I've noticed is that you have committed the file into the `develop` branch. The bot won't pick it up there unless it's told to do so.

* If you don't want to have the file in `master`, you'll need to set the branch manually on the web ui.
* If it's okay to have the file in `master`, but you want pull requests to happen against `develop`, add `branch: develop` to the config file and add it to the master branch.
* If it's okay to have the file in master and pull request agains master, just add it to the master branch.

**Comment by mimischi** [comment]
Obviously I'm stupid and too lazy to read, thank you very much! I just haven't pushed the newest updates to the master branch yet, so that should work then.

On a related note: are you planning to provide badges on a per-branch basis (just as require.io does)?

**Comment by Pawamoy** [comment]
Can pyup find dependencies in tox.ini if I add it to the requirements section of the configuration file?

```yaml
requirements:
  - requirements/base.txt
  - tox.ini
```

**Comment by keimlink** [comment]
Support for tox.ini would be awesome. We define some dependencies using the deps setting. To be sure all tox envs use the same version of doc8 or flake8 we pin them. At the moment pyup does not update the dependencies and so we have to update them manually.

**Comment by keimlink** [comment]
@jayfk Can you please update us on the current status of tox.ini support? Thanks!

**Comment by jayfk** [comment]
@keimlink I have a local dev branch with read support for tox and conda files. Next step: adding write support!

I'm currently looking for reasonably complicated tox.ini files. It'd great to add this with a good initial test coverage.

**Comment by keimlink** [comment]
Great news!

This is one of our `tox.ini` files. Feel free to use it.

```
[tox]
envlist = bandit,flake8,isort,manifest,yamllint,portable-objects,docs,compile-requirements,py35
minversion = 2.4.0

[testenv]
commands =
    pip install --constraint requirements/constraints.pip --requirement requirements/test.pip
    make bundles-development coverage
install_command = pip install --constraint requirements/constraints.pip {opts} {packages}
passenv =
    CIRCLE_*
    DATABASE_URL
    ENV
    PYTEST_ADDOPTS
whitelist_externals =
    git
    make
    rm
extras =
    raven
    whitenoise

[testenv:bandit]
commands =
    bandit --ini setup.cfg -ii -l --recursive project_directory
deps =
    bandit==1.4.0
skip_install = True

[testenv:flake8]
commands =
    make flake8
deps =
    flake8==3.3.0
skip_install = True

[testenv:isort]
commands =
    make isort-check
deps =
    isort==4.2.15
skip_install = True

[testenv:manifest]
commands =
    check-manifest --verbose
deps =
    check-manifest==0.34
skip_install = True

[testenv:yamllint]
commands =
    make yamllint
deps =
    yamllint==1.8.1
skip_install = True

[testenv:portable-objects]
commands =
    make portable-objects-lint
deps =
    dennis==0.9
skip_install = True

[testenv:docs]
commands =
    make install-documentation
    make docs BUILDDIR={envtmpdir} SPHINXOPTS='{env:SPHINXOPTS_BUILD:-W}'
    make --directory=docs linkcheck BUILDDIR={envtmpdir} SPHINXOPTS='{env:SPHINXOPTS_LINKCHECK:}'
    doc8
deps =
    doc8==0.8.0
passenv =
    {[testenv]passenv}
    SPHINXOPTS_BUILD
    SPHINXOPTS_LINKCHECK

[testenv:compile-requirements]
commands =
    rm -f heroku/requirements.txt
    pip-compile --output-file heroku/requirements.txt --rebuild --verbose requirements/constraints.pip requirements/production.in
    git checkout -- heroku/requirements.txt
deps =
    pip-tools==1.9.0
setenv =
    PIP_FIND_LINKS={distdir}
skip_install = True
```

Last time we fed it to pyup it thought `whitelist_externals` is a list of Python packages. :rofl:

**Comment by jayfk** [comment]
> Last time we fed it to pyup it thought whitelist_externals is a list of Python packages. 🤣

Bots 🤦‍♂️ .

I've created a WIP branch here in case you want to track it: https://github.com/pyupio/pyup/pull/222

**Comment by jayfk** [comment]
I've decided to split the requirements parsing part into it's own library, here: https://github.com/pyupio/dparse

While it takes a little bit more time to get things right, the whole Python packaging community can use it without pulling in the whole bot as a dependency.

I'll probably have something ready by the end of the week.

**Comment by jayfk** [comment]
Support for `tox.ini` and `conda_env.yml` files is now live 👏 

It's still a bit experimental, so don't rely on it for your pacemaker's Python dependencies.

Support for [Pipfile](https://github.com/pyupio/pyup/issues/197), [Pipfile.lock](https://github.com/pyupio/pyup/issues/197), [setup.py](https://github.com/pyupio/pyup/issues/137) and eventually zc.bildout are planned.
